git:
  depth: 3
branches:
  except:
  - docs
language: node_js
node_js:
- '8'
script:
- npm run test
- npm run lint
- cd ./frontend/ && npm install && npm run build
- cd .. && npm install
deploy:
  provider: heroku
  app: enigmatic-springs-58797
  skip_cleanup: true
  on:
    all_branches: true
    condition: true
  api_key:
    secure: jGJlh5x1+eAJDnaYNzAJylkcSfhMK+n2s9tSofLqyiWg0KIdDyVAwCAJp2Tic0c5Iggj7j4DsVIEbm5iAN+OPyeT8l6ABemjjoBLHYTD4w/PkiAdF2gb+Fxz1TxRbbuhaqu8qlRzFW3yeLN0jok6+flolJUgLaWXrLaWqxeDHPGmeuS7RibId6d8WXuwmxBAFCFuXiLouLjvof/TvppGaHxnQxsPADG+it5/tzfp2BU9Vs1t+vXtmObi4RzvNhi6Oh/YNBlKjUEB3oSVqmTp2EqfLjS/EVgQ/46ssmb7241FkBvYHIE9so5MzVA7pmK7mPSfHT9yARqr/dIs37fO/YDVVSAilcvAEZ5S63oe3/i6KDWOIwUiTaXsl6U2MHy8skV3NJ5yLnsebLxlk4x2XV05dJmi+QhkWuEbEbYlkGGo0fQS19LiOrrTkJrry3uQW8ImKz8dRtHmbIcjRpFvnCRzpxpQ4yXB6ZwEebX84r23++DurGkBEK65Kl//5eI6Lufnc+t2NKKSAc0D6WijT7h51jlzl6H1f5KYTXzyso8VKW39gFmrYu7ILTSUQUskLrMNPRWDwmZvHH4RD5xuyX5BcbpOkhiDq8b0FJ/EiLs9jUBR6k0UF8c4RywAFEbL9W5fYA9XCL3Q0Pt9HsDEKHKAxFbhINUr0OP51mVCRl8=
